* Log-sum-exp and softmax and functions

* About

=logsumexp= and =softmax= and evaluate the 
log-sum-exp function 
and the 
softmax function of a vector x.  
Softmax is the derivative of log-sum-exp.
$\mathrm{lse}(x) = \log \sum_{i=1}^n \mathrm{e}^{x_i}$.

${lse}(x) = \log \sum_{i=1}^n {e}^{x_i}$.

Other program files are

- =test=: runs some simple tests of the functions.

* Usage

The lines
#+begin_src 
sm = softmax(x)
[sm,lse] = softmax(x)
lse = logsumexp(x)
[lse,sm] = logsumexp(x)
#+end_src

compute the softmax sm and the log-sum-exp lse at the vector x.
Both functions can compute both quantities because there is significant 
overlap in the computations of the two functions.

* Requirements

The code was developed in MATLAB R2020b and works with versions
back to at least R2017a.

* References

P. Blanchard, D. J. Higham, and N. J. Higham.  
[[Doi:10.1093/Imanum/Draa038][Computing the Log-Sum-Exp and Softmax Functions]]. 
IMA J. Numer. Anal., Advance access, 2020.

* License

See =license.txt= for licensing information.
